---
title: "BIOCLIM"
author: "Irene Extremera Serrano"
date: "9/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE, warning = FALSE, error = FALSE, message = FALSE, comment = " ")
```

###########################
####### Librerías #########
###########################

````{r, warning=FALSE, message=FALSE, echo= FALSE}

library(sp) #Tabajar con objetos de tipo espacial
library(rgdal) #Es necesaria para la librería sdmpredictors
library(carData)
library(car)
library(nlme)
library(gstat)
library(sf)
library(spData)
library(spdep)
library(lattice)
library(survival)
library(Formula)
library(ggplot2) #Para gráficos de las predicciones
library(Hmisc)
library(raster) #Para poder trabajar con objetos tipo raster
library(leaflet)
library(GGally)
library(maptools)
library(corrplot)
library(rgeos)
library(maptools) #Cargar mapas
library(dismo) #Para poder trabajar con BIOCLIM y MAXENT
library(sdmpredictors) #Para descargarme las variables ambientales
library(PresenceAbsence)
library(rJava)
library(randomForest)
library(INLA) #Para trabajar con INLA
library(Matrix)
library(parallel)
library(foreach)
library(dotCall64)
library(grid)
library(spam)
library(fields)
library(randomForest) #Para realizar Random Fores
library(gbm) #Para realizar vosted regression tree
library(TeachingDemos)
library(raster)
library(stars)
library(mgcv)
```

#####################################################################
####### Bases de datos, predictores, modelos y coeficientes #########
#####################################################################

```{r, echo= FALSE}

# Directorio de trabajo

setwd("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/Rmd")

# Mapa del mundo
data(wrld_simpl) 

#Presencias
data <- read.csv('C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/Datos/Anchoas_Aqua_atln.csv',TRUE,",")
data <- data[,-1] #Le quito al primera que es una columna de índices
colnames(data) <- c('Lon','Lat') #Le doy nombre a las columnas

#Predictores modelo
cuatro_pred <- (list.files("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/Predictores/atl/Seleccionadas", full.names=T, pattern=".tif")) #Cargo bathy que lo he metido en una carpeta aparte
predictors <- stack(cuatro_pred)
names(predictors) <- c("bathy","odismean","salinity","tempmean")
predictors3 <- scale(predictors)

# Predictores con RAC
files<-(list.files("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/Predictores/RAC/BIOCLIM", full.names=T, pattern=".tif"))
predictors <- stack(files)
names(predictors) <- c("bathy","odismean","salinity","focal_rac_vect","tempmean")
predictors_rac <- scale(predictors) 

# Ausencias (Con todos los predictores pues es así como se han creado para meterlas al sdmdata_modelos)
files<-(list.files("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/Predictores/atl", full.names=T, pattern=".tif"))#change directory
predictores <- stack(files)
names(predictores) <- c("bathy","chlomean","ppmean","odismean","salinity","tempmean")
predictors2 <- scale(predictores) #Los escalo

#Background
set.seed(141592) 
backgr <- randomPoints(predictors2, 1000) 

# Base de datos sin RAC.
sdmdata <- read.csv("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/Datos/sdmdata_atln_modelos.csv")
sdmdata <- sdmdata[,-1]

# Para comprobar que todo está en orden
plot(wrld_simpl,xlim=c(-11,9),ylim=c(43,60))
points(sdmdata[,6],sdmdata[,7])

# Modelo
bc.model <- readRDS("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/bc.model.rds")

# Predictiva
predict_presence_bc_bioclim<-readRDS( "C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/Predicciones_BIOCLIM_Atl.ascii")

# Coeficientes
coef_bc_model <-  read.csv("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/coeficientes_BIOCLIM.csv")
cosites_bc_model <- read.csv("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/coeficientes_BIOCLIM_todos.csv")
cosites_bc_model<- cosites_bc_model[,c(-1)]

# Predictores con RAC
files<-(list.files("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/Predictores/RAC/BIOCLIM", full.names=T, pattern=".tif"))
predictors <- stack(files)
names(predictors) <- c("bathy","odismean","salinity","focal_rac_vect","tempmean")
predictors_rac <- scale(predictors) 

#### CON COMPONENTE ESPACIAL ####
ddd<- read.csv('C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/Datos/rac_bioclim.csv') #Base de datos con RAC
ddd<-ddd[,-1]
ddd$focal_rac_vect<-extract(predictors_rac$focal_rac_vect, ddd$x,ddd$y) #Mete los valores de rac escalados
ddd<-na.omit(ddd)#Elimina los NAs

# Modelo RAC
bc.model_rac<- readRDS("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/bc.model_rac.rds")

#Predictiva RAC
predict_presence_bc_bioclim_rac  <- readRDS("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/Predicciones_BIOCLIM_Atl_rac.ascii")

#Coeficientes RAC
cosites_bc_model_rac <- read.csv('C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/coeficientes_BIOCLIM_todos_rac.csv')
cosites_bc_model_rac<-cosites_bc_model_rac[,-1]
coef_bc_model_rac <- read.csv('C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/coeficientes_BIOCLIM_media_rac.csv')
```

###########################
##### --- BIOCLIM --- #####
###########################

# Modelo

```{r}

bc.model <- bioclim(x = predictors3, p = data)
bc.model
plot(bc.model)

# Guardo el modelo
saveRDS(bc.model, "C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/bc.model.rds")

```

# Predictiva

```{r}

# Predictiva de presencias
ext <-extent(-11,9,43,60) #Para Atlántico Norte

predict_presence_bc_bioclim <- predict(object = bc.model,
                                   x = predictors3,
                                   ext = ext)

# La pinto
ggplot() +
  geom_raster(data = raster::as.data.frame(predict_presence_bc_bioclim , xy = TRUE) , aes(x = x, y = y, fill = layer)) +
  coord_equal() +
  labs( x = "", y = "")+theme_minimal()+
  scale_color_brewer(palette = 'YlGnBu')+ labs(fill='') +
  guides(fill = guide_legend(label.position = "left", label.hjust = 1))

# La guardo
saveRDS(predict_presence_bc_bioclim, "C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/Predicciones_BIOCLIM_Atl.ascii")

```

# Validación cruzada

```{r}

# FUNCIÓN DEFINITIVA DEFINITIVÍSIMA MILENARIA XTREM para BIOCLIM.

fddmx <- function(coordenadas, predictores,background){

      group <- kfold(coordenadas, 5)

      pres_train <- coordenadas[group != 1, ] #Las que no sean 1
      pres_test <- coordenadas[group == 1, ] #Las que sean 1
      
      bc <- bioclim(predictores, pres_train)

      group <- kfold(background, 5) #Hago 5 grupos de esos puntos
      backg_train <- background[group != 1, ]
      backg_test <- background[group == 1, ]
      
      eval.modesta <- evaluate(pres_test, backg_test, bc, predictores)
      
      auc_model <- eval.modesta@auc #auc
      
      cor_model <- eval.modesta@cor #cor
      
      kappa_model <- mean(eval.modesta@kappa) #Kappa

      sensibility_model <- mean(eval.modesta@TPR/(eval.modesta@TPR+eval.modesta@FNR)) #Sensibilidad
      
      specificity_modelo <- mean(eval.modesta@TNR/(eval.modesta@FPR+eval.modesta@TNR)) #Especificidad
      
      TSS_model <- mean(eval.modesta@TPR+eval.modesta@TNR-1) #TSS
      
      return(c(auc_model,cor_model,kappa_model,sensibility_model,specificity_modelo,TSS_model))
}

# Hago una matriz para guardar los valores de los coeficientes de las diez iteraciones que me devuelva la función 
cosites_bc_model <- matrix(ncol=6,nrow=10) 
      
# Genereo un bucle for de 10 iteraciones que me devuelva 10 valores diferentes de los 6 coeficientes.
for (i in 1:10) { cosites_bc_model[i,] <- fddmx(data,predictors3,backgr)}

# Le doy nombre a las columnas para saber qué coeficientes hay dentro
colnames(cosites_bc_model) <- c('AUC','COR','Kappa','Sensitivity','Specificity','TSS')

# Hago la media por columnas que es lo que me interesa y lo guardo
coef_bc_model <- apply(cosites_bc_model, 2, mean)
write.csv(coef_bc_model,'C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/coeficientes_BIOCLIM_media.csv')#Guardo los coeficientes
write.csv(cosites_bc_model,'C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/coeficientes_BIOCLIM_todos.csv')#Guardo los coeficientes sin hacer la media

```

# Autocorrelación espacial

```{r}

### AUTOCORRELACIÓN ESPACIAL ###
bc_pred_val<-extract(predict_presence_bc_bioclim,data) #Extraigo los valores de predicción para esas coordenadas
res_bc <- bc_pred_val-1 #Calculo residuos de solo presencias (1)
res_bc <- na.omit(bc_pred_val) 

nb <- dnearneigh(as.matrix(data), 1,max(data));nb
listw <- nb2listw(nb,style = "S")

#Realizo el test de Moran
MoranI_bc <- moran.test(res_bc, listw=listw, randomisation=FALSE); MoranI_bc #El p valor de 1 me indica que no hay autocorrelación espacial
Moran_MC_bc <- moran.mc(res_bc, listw=listw, nsim=100); Moran_MC_bc #p valor de 0.99 no se rechaza Ho, lo cual indica que no hay autocorrelación espacial

```

No hay autocorrelación espacial.

####################################
##### --- BIOCLIM ESPACIAL --- #####
####################################

# RAC: Introducción de la componente espacial.

```{r}

########    RAC   ###################
# Extraer los residuos del modelo de BIOCLIM y mapearlos
r<- raster(xmn=-11, xmx=9, ymn=43, ymx=60, nrows=324, ncols=660);r #Hago un raster grande
res(r) <‐ 0.083 #Le doy una resolución de 0.083
xy <-cbind(data$Lon, data$Lat)#Cojo las coordenadas
xy_residuals <-cbind(xy, res_bc) #Uno las coordenadas y los residuos a un mismo objeto

par(mfrow=c(1,2))
r[cellFromXY(r, xy_residuals)] <-xy_residuals[,3] #Doy esos valores de residuos a esas coordenadas
plot(r,col='red') #Efectivamente me salen residuos, pero no en todo el area
ext <- c(-11,9,43,60) #Extensión a cortar
salinity <- raster("C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/Predictores/RAC/MAXENT/salinity_atln.TIF") #Cargo este raster para poder ajustar el raster r
r <- resample(r,salinity) #Ajusto las dimensiones de r a las de salinity
r<-crop(r,ext);r #Lo corto
writeRaster(r, filename="RAC_bc_atln.tif", format="GTiff", overwrite=TRUE) #Lo guado en el wd

#Calculo los residuos autocovariados
focal_rac_rast <-focal(r, w=matrix(1,3,3), fun = mean,  na.rm = TRUE)

#Extraigo los valores de la operación focal del objeto focal_rac_rest usando las coordinadas guardadas en xy
focal_rac_vect <-extract(focal_rac_rast, xy)
length(focal_rac_vect)

#Añado los valores de la componente espacial a la base de datos
dd<-cbind(data, focal_rac_vect)
I <- is.na(dd$focal_rac_vect)
ddd<- dd[!I,]
dim(dd)
dim(ddd)
write.csv(ddd, 'C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/Datos/rac_bioclim .csv')

```

# Kriging con RAC: Pintar el mapa entero

```{r}

salinity <- load_layers(c("BO_salinity"))
e<-extent(-11,9,43,60) #Extensión con la que trabajo
sal=crop(salinity,e) #Corto el raster

# Lo pinto
plot(sal)
points(ddd$x,ddd$y)

#Saco las coordenadas de uno de los rasters. 
loci1 <-as.data.frame(coordinates(sal))
summary(loci1)

x.range <- as.numeric(c(-10.958, 8.958))  # min/max longitud del area de interpolación 
y.range <- as.numeric(c(42.04,59.96))  #in/max latitud del area de interpolación 
grd <- expand.grid(x = seq(from = x.range[1], to = x.range[2], by =  0.08333333), y = seq(from = y.range[1], 
                                                                                          to = y.range[2], by =  0.08333333))  # expando los puntos sobre el grid
coordinates(grd) <- ~x + y #Coordenadas del grid
proj4string(grd) <- CRS("+init=epsg:4326") #Coordenadas geográficas
gridded(grd)     <- TRUE  # Crea un objeto SpatialPixel 
fullgrid(grd)    <- TRUE  # Crea un objeto SpatialGrid 

coords <- cbind(ddd$x,ddd$y) #Asigno coordenadas
matrix<-cbind(ddd$focal_rac_vect, ddd[,c(1,2)]) #Uno las coordenadas a los valores de rac
matrix<-as.data.frame(matrix) #Lo paso a data.frame
colnames(matrix)<-c("Pred","Lon","Lat") #Renombro

coordinates(matrix) <- c("Lon", "Lat")  #Doy nombre a las coordenadas
proj4string(matrix) <- CRS("+init=epsg:4326") #Coordenadas geográficas

#Interpolo a las células del grid.
rac <- gstat::idw(Pred~ 1, locations = matrix, newdata=grd, idp=0.1) 

# Plot
plot(rac,col=tim.colors(100)[1:100],main=" ", axes=T)
data(wrld_simpl)
plot(wrld_simpl, add=TRUE,col='dark grey')

#convertir a raster
RAC=as.data.frame(rac) #Paso la interpolación a data.frame
coordinates(RAC) <- ~ x + y #Le asigno unas coordenadas
gridded(RAC) <- TRUE #Creo un objeto pixelado espacial
RAC <- raster(RAC) #Lo transformo en raster

plot(RAC)

#####################################################
#  Corto con bathy 
##################################################

depth<- load_layers(c("MS_bathy_5m")) #Cargo batimetría
depth=crop(depth,e) #La corto
depth=abs(depth) ##función abs convierte en positivo ### formato raster

## Transformo en data.frame

matrix<- cbind(coordinates(depth), depth=getValues(depth)) #Cojo los valores de batimetría para esas coordenadas
I <- is.na(matrix[,3]) #Identifico NAs
matrix<- matrix[!I,] #Quito los NAs
matrix<-as.data.frame(matrix) #Transformo a data.frame
new<- subset(matrix, matrix$depth > 0) ###trocar profundidade

###transformar data.frame em raster de nuevo

xy <- cbind(new$x, new$y) #Me quedo con las coordenadas
rast<- raster(xmn=-11, xmx=9, ymn=43, ymx=60, nrows=276, ncols=624)#2  
p<- rasterize(xy, rast, new$depth, fun=max,na.rm=F) #Hago un raster
p<-resample(p,sal) #Le doy las dimensiones de salinidad
e<-extent(p) 

sp<-crop(RAC,e)
sp=resample(sp,p)
sp<-raster::mask(sp,p)


# Plot
plot(sp,col=tim.colors(100)[1:100],main=" ", axes=T)
data(wrld_simpl)
plot(wrld_simpl, add=TRUE,col='dark grey')

plot(RAC,col=tim.colors(100)[1:100],main=" ", axes=T)
data(wrld_simpl)
plot(wrld_simpl, add=TRUE,col='dark grey')

writeRaster(sp, filename="sp_bc_atln.tif", format="GTiff", overwrite=TRUE)

```

# Modelo espacial

```{r}

bc.model_rac <- bioclim(x = predictors_rac, p = data)

# Guardo el modelo
saveRDS(bc.model_rac, "C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/bc.model_rac.rds") #Guardo el modelo BIOCLIM

```

# Predictiva 

```{r}

# Predictiva de presencias
predict_presence_bc_bioclim_rac <- predict(object = bc.model_rac,
                                   x = predictors_rac,
                                   ext = ext)

# La pinto
ggplot() +
  geom_raster(data = raster::as.data.frame(predict_presence_bc_bioclim_rac , xy = TRUE) , aes(x = x, y = y, fill = layer)) +
  coord_equal() +
  labs( x = "", y = "")+theme_minimal()+
  scale_color_brewer(palette = 'YlGnBu')+ labs(fill='') +
  guides(fill = guide_legend(label.position = "left", label.hjust = 1))

# La guardo
saveRDS(predict_presence_bc_bioclim_rac, "C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/Predicciones_BIOCLIM_Atl_rac.ascii")

```

# CV

```{r}
# Hago una matriz para guardar los valores de los coeficientes de las diez iteraciones que me devuelva la función 
cosites_bc_model_rac <- matrix(ncol=6,nrow=10) 
      
# Genereo un bucle for de 10 iteraciones que me devuelva 10 valores diferentes de los 6 coeficientes.
for (i in 1:10) { cosites_bc_model_rac[i,] <- fddmx(data,predictors_rac,backgr)}

# Le doy nombre a las columnas para saber qué coeficientes hay dentro
colnames(cosites_bc_model_rac) <- c('AUC','COR','Kappa','Sensitivity','Specificity','TSS')

# Hago la media por columnas que es lo que me interesa y lo guardo
coef_bc_model_rac <- apply(cosites_bc_model_rac, 2, mean)
write.csv(coef_bc_model_rac,'C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/coeficientes_BIOCLIM_media_rac.csv')#Guardo los coeficientes
write.csv(cosites_bc_model_rac,'C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/coeficientes_BIOCLIM_todos_rac.csv')#Guardo los coeficientes sin hacer la media

```

# Autocorrelación espacial

```{r}
### AUTOCORRELACIÓN ESPACIAL ###
bc_pred_val_rac<-extract(predict_presence_bc_bioclim_rac,data) 
res_bc_rac<- bc_pred_val_rac-1 #Calculo residuos de solo presencias
res_bc_rac <- na.omit(res_bc_rac)

nb <- dnearneigh(as.matrix(data), 1,max(data));nb
listw <- nb2listw(nb,style = "S")

#Realizo el test de Moran
MoranI_bc_rac <- moran.test(res_bc_rac, listw=listw, randomisation=FALSE); MoranI_bc_rac #El p valor de 1 me indica que no hay autocorrelación espacial
Moran_MC_bc_rac <- moran.mc(res_bc_rac, listw=listw, nsim=100); Moran_MC_bc_rac #p valor de 0.99 no se rechaza Ho, lo cual indica que no hay autocorrelación espacial

cosis <- c(Moran_MC_bc$p.value,MoranI_bc$p.value, Moran_MC_bc_rac$p.value, MoranI_bc_rac$p.value)
ind_m_bio <- matrix(cosis,ncol=2, nrow=2 )
colnames(ind_m_bio) <- c("Moran MC", "Moran I")
rownames(ind_m_bio) <- c("Sin EE","Con EE")
write.csv(ind_m_bio,'C:/Users/Irene/Source/Repositorios/TFM-Irene-Extremera/BIOCLIM/coeficientes_BIOCLIM_moran.csv')
```